name = "EoM_sketch"
uuid = "1ddccac4-7cb4-11e9-0a9b-23bf2429f75d"
authors = ["BPMinaker <bminaker@uwindsor.ca>"]
version = "0.1.0"

[deps]
EoM = "25d7ee20-f19a-11e8-093a-7b526cbd2d90"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
